# Generated by Django 3.0 on 2020-07-31 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordTypeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.TextField()),
                ('word_es', models.TextField()),
                ('word_times', models.IntegerField(default=0)),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_english_dic.WordTypeItem')),
            ],
            options={
                'verbose_name': 'English/Spanish Word',
                'verbose_name_plural': 'English/Spanish Words',
            },
        ),
    ]
