# Generated by Django 3.1 on 2020-08-13 09:03

import app_english_dic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_english_dic', '0002_auto_20200813_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worditem',
            name='word_times',
            field=models.IntegerField(default=app_english_dic.models.WordItem.word_times_default, null=True),
        ),
    ]
