# Generated by Django 3.1 on 2020-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_english_dic', '0003_auto_20200813_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worditem',
            name='word_times',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
