# Generated by Django 3.0 on 2020-05-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 14, 29, 42, 205435)),
        ),
    ]
