# Generated by Django 3.0 on 2020-05-25 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 14, 40, 26, 466009, tzinfo=utc)),
        ),
    ]
