# Generated by Django 3.0 on 2020-05-25 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200525_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
