# Generated by Django 3.0 on 2020-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritem',
            name='author_surname',
            field=models.TextField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='authoritem',
            name='author_name',
            field=models.TextField(max_length=30),
        ),
    ]
