# Generated by Django 3.1 on 2020-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdataitem',
            old_name='Humidity data',
            new_name='weather_humidity',
        ),
        migrations.RenameField(
            model_name='weatherdataitem',
            old_name='Rain data',
            new_name='weather_rain',
        ),
        migrations.RenameField(
            model_name='weatherdataitem',
            old_name='Temperature data',
            new_name='weather_temp',
        ),
    ]
