# Generated by Django 3.1 on 2020-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_auto_20200828_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityitem',
            name='weather_url',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
