# Generated by Django 3.1 on 2020-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_cityitem_weather_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdataitem',
            name='weather_wind',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
