# Generated by Django 3.1 on 2020-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0002_auto_20200807_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoritem',
            name='author_surname',
            field=models.TextField(blank=True, default='', max_length=60, null=True),
        ),
    ]
